/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import User.Information;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JComboBox;

import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author srush
 */
public class CreateMainJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateMainJPanel
     */
    private final Information information;

    public CreateMainJPanel(Information information) {
        initComponents();
        this.information = information;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fNameJLabel = new javax.swing.JLabel();
        fNameJText = new javax.swing.JTextField();
        lastNameJLabel = new javax.swing.JLabel();
        lastNameJText = new javax.swing.JTextField();
        phoneNumJLabel = new javax.swing.JLabel();
        phoneNumJText = new javax.swing.JTextField();
        dobJLabel = new javax.swing.JLabel();
        dobJText = new javax.swing.JTextField();
        ageJLabel = new javax.swing.JLabel();
        ageJText = new javax.swing.JTextField();
        heightJLabel = new javax.swing.JLabel();
        heightJText = new javax.swing.JTextField();
        weightJLabel = new javax.swing.JLabel();
        weightJText = new javax.swing.JTextField();
        ssnJLabel = new javax.swing.JLabel();
        ssnJText = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        add1JLabel = new javax.swing.JLabel();
        add1JText = new javax.swing.JTextField();
        add2JLabel = new javax.swing.JLabel();
        add2JText = new javax.swing.JTextField();
        cityJLabel = new javax.swing.JLabel();
        cityJText = new javax.swing.JTextField();
        stateJLabel = new javax.swing.JLabel();
        stateJText = new javax.swing.JTextField();
        zipCodeJLabel = new javax.swing.JLabel();
        zipCodeJText = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        savingsBankNameJLabel = new javax.swing.JLabel();
        savingsBankNameJText = new javax.swing.JTextField();
        savingsAccBalnJLabel = new javax.swing.JLabel();
        savingsAccBalnJText = new javax.swing.JTextField();
        savingsRNumJLabel = new javax.swing.JLabel();
        savingsRNumJText = new javax.swing.JTextField();
        savingsAccNumJLabel = new javax.swing.JLabel();
        savingsAccNumJText = new javax.swing.JTextField();
        savingsAccTypeJLabel = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        uploadeImageJButton = new javax.swing.JButton();
        pictureJText = new javax.swing.JTextField();
        licenseNumJLabel = new javax.swing.JLabel();
        licenseNumJText = new javax.swing.JTextField();
        dateIssueJLabel = new javax.swing.JLabel();
        dateIssueJText = new javax.swing.JTextField();
        dateExpiryJLabel = new javax.swing.JLabel();
        dateExpiryJText = new javax.swing.JTextField();
        bloodTypeJLabel = new javax.swing.JLabel();
        bloodTypeJText = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        medicalRecordNumJLabel = new javax.swing.JLabel();
        medicalRecordNumJText = new javax.swing.JTextField();
        alergy1JLabel = new javax.swing.JLabel();
        alergy1JText = new javax.swing.JTextField();
        alergy2JLabel = new javax.swing.JLabel();
        alergy2JText = new javax.swing.JTextField();
        alergy3JLabel = new javax.swing.JLabel();
        alergy3JText = new javax.swing.JTextField();
        createReportJButton = new javax.swing.JButton();
        demographicJLabel = new javax.swing.JLabel();
        addressDetailsJLabel = new javax.swing.JLabel();
        savingsAccountDetailsJLabel = new javax.swing.JLabel();
        lincenseDetailsJLabel = new javax.swing.JLabel();
        medicalDetailsJLabel = new javax.swing.JLabel();
        ImageHolder = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        checkingsBankNameJLabel = new javax.swing.JLabel();
        checkingsBankNameJText = new javax.swing.JTextField();
        checkingsAccBalnJLabel = new javax.swing.JLabel();
        checkingsAccBalnJText = new javax.swing.JTextField();
        checkingsRNumJLabel = new javax.swing.JLabel();
        checkingsRNumJText = new javax.swing.JTextField();
        checkingsAccNumJLabel = new javax.swing.JLabel();
        checkingsAccNumJText = new javax.swing.JTextField();
        checkingsAccTypeJLabel = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();

        setMinimumSize(new java.awt.Dimension(900, 800));
        setPreferredSize(new java.awt.Dimension(900, 800));

        jPanel1.setBackground(new java.awt.Color(227, 246, 245));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 800));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Fill Personal Information to Create Report");

        fNameJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        fNameJLabel.setText("First Name:");

        fNameJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        fNameJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lastNameJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lastNameJLabel.setText("Last Name:");

        lastNameJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lastNameJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        lastNameJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameJTextActionPerformed(evt);
            }
        });

        phoneNumJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        phoneNumJLabel.setText("Phone #:");

        phoneNumJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        phoneNumJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        phoneNumJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumJTextActionPerformed(evt);
            }
        });

        dobJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        dobJLabel.setText("DOB:");

        dobJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        dobJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        dobJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobJTextActionPerformed(evt);
            }
        });

        ageJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ageJLabel.setText("Age:");

        ageJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ageJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ageJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageJTextActionPerformed(evt);
            }
        });

        heightJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        heightJLabel.setText("Height:");

        heightJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        heightJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        heightJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightJTextActionPerformed(evt);
            }
        });

        weightJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        weightJLabel.setText("Weight:");

        weightJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        weightJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        weightJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightJTextActionPerformed(evt);
            }
        });

        ssnJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ssnJLabel.setText("SSN #:");

        ssnJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        ssnJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ssnJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssnJTextActionPerformed(evt);
            }
        });

        add1JLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        add1JLabel.setText("Street Address:");

        add1JText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        add1JText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        add2JLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        add2JLabel.setText("Apartment:");

        add2JText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        add2JText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        add2JText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2JTextActionPerformed(evt);
            }
        });

        cityJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cityJLabel.setText("City:");

        cityJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cityJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        cityJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityJTextActionPerformed(evt);
            }
        });

        stateJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        stateJLabel.setText("State");

        stateJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        stateJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        stateJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateJTextActionPerformed(evt);
            }
        });

        zipCodeJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        zipCodeJLabel.setText("Zip Code");

        zipCodeJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        zipCodeJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        zipCodeJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipCodeJTextActionPerformed(evt);
            }
        });

        savingsBankNameJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        savingsBankNameJLabel.setText("Bank Name");

        savingsBankNameJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        savingsBankNameJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        savingsAccBalnJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        savingsAccBalnJLabel.setText("Account Balance:");

        savingsAccBalnJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        savingsAccBalnJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        savingsAccBalnJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsAccBalnJTextActionPerformed(evt);
            }
        });

        savingsRNumJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        savingsRNumJLabel.setText("Routing #:");

        savingsRNumJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        savingsRNumJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        savingsRNumJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsRNumJTextActionPerformed(evt);
            }
        });

        savingsAccNumJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        savingsAccNumJLabel.setText("Account #:");

        savingsAccNumJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        savingsAccNumJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        savingsAccNumJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsAccNumJTextActionPerformed(evt);
            }
        });

        savingsAccTypeJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        savingsAccTypeJLabel.setText("Account Type:");

        uploadeImageJButton.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        uploadeImageJButton.setText("Upload");
        uploadeImageJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadeImageJButtonActionPerformed(evt);
            }
        });

        pictureJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        pictureJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pictureJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pictureJTextActionPerformed(evt);
            }
        });

        licenseNumJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        licenseNumJLabel.setText("License #:");

        licenseNumJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        licenseNumJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        dateIssueJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        dateIssueJLabel.setText("Issued on:");

        dateIssueJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        dateIssueJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        dateIssueJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateIssueJTextActionPerformed(evt);
            }
        });

        dateExpiryJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        dateExpiryJLabel.setText("Expiry:");

        dateExpiryJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        dateExpiryJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        dateExpiryJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateExpiryJTextActionPerformed(evt);
            }
        });

        bloodTypeJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        bloodTypeJLabel.setText("Blood Type:");

        bloodTypeJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        bloodTypeJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bloodTypeJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodTypeJTextActionPerformed(evt);
            }
        });

        medicalRecordNumJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        medicalRecordNumJLabel.setText("Medical Recored #:");

        medicalRecordNumJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        medicalRecordNumJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        alergy1JLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        alergy1JLabel.setText("Alergy 1:");

        alergy1JText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        alergy1JText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        alergy1JText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alergy1JTextActionPerformed(evt);
            }
        });

        alergy2JLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        alergy2JLabel.setText("Alergy 2:");

        alergy2JText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        alergy2JText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        alergy2JText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alergy2JTextActionPerformed(evt);
            }
        });

        alergy3JLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        alergy3JLabel.setText("Alergy 3:");

        alergy3JText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        alergy3JText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        alergy3JText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alergy3JTextActionPerformed(evt);
            }
        });

        createReportJButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        createReportJButton.setText("Save & Submit");
        createReportJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createReportJButtonActionPerformed(evt);
            }
        });

        demographicJLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        demographicJLabel.setText("Demographic:");

        addressDetailsJLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        addressDetailsJLabel.setText("Address Details:");

        savingsAccountDetailsJLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        savingsAccountDetailsJLabel.setText("Account Details:");

        lincenseDetailsJLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lincenseDetailsJLabel.setText("License Details:");

        medicalDetailsJLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        medicalDetailsJLabel.setText("Medical Records Details:");

        ImageHolder.setBackground(new java.awt.Color(255, 255, 255));
        ImageHolder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ImageHolder.setText("Please Upload your picture");
        ImageHolder.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ImageHolder.setMinimumSize(new java.awt.Dimension(200, 200));
        ImageHolder.setPreferredSize(new java.awt.Dimension(200, 200));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Account type", "Savings", "Checking" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        checkingsBankNameJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        checkingsBankNameJLabel.setText("Bank Name");

        checkingsBankNameJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        checkingsBankNameJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        checkingsAccBalnJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        checkingsAccBalnJLabel.setText("Account Balance:");

        checkingsAccBalnJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        checkingsAccBalnJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        checkingsAccBalnJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingsAccBalnJTextActionPerformed(evt);
            }
        });

        checkingsRNumJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        checkingsRNumJLabel.setText("Routing #:");

        checkingsRNumJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        checkingsRNumJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        checkingsRNumJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingsRNumJTextActionPerformed(evt);
            }
        });

        checkingsAccNumJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        checkingsAccNumJLabel.setText("Account #:");

        checkingsAccNumJText.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        checkingsAccNumJText.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        checkingsAccNumJText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingsAccNumJTextActionPerformed(evt);
            }
        });

        checkingsAccTypeJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        checkingsAccTypeJLabel.setText("Account Type:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Account type", "Savings", "Checking" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jSeparator8.setPreferredSize(new java.awt.Dimension(600, 10));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(checkingsRNumJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkingsRNumJText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkingsAccNumJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(checkingsAccNumJText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(checkingsBankNameJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkingsBankNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(checkingsAccBalnJLabel)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(checkingsAccTypeJLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(checkingsAccBalnJText, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(demographicJLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(savingsBankNameJLabel)
                                        .addGap(3, 3, 3))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(savingsRNumJLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(savingsBankNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(savingsAccBalnJLabel))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(savingsRNumJText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(savingsAccNumJLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(savingsAccNumJText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(savingsAccBalnJText, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(savingsAccTypeJLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(add1JLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add1JText, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(add2JLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add2JText, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(savingsAccountDetailsJLabel)
                            .addComponent(addressDetailsJLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dobJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dobJText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(ageJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ageJText, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(heightJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(heightJText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(weightJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(weightJText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ssnJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ssnJText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fNameJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lastNameJLabel)
                                .addGap(18, 18, 18)
                                .addComponent(lastNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(phoneNumJLabel)
                                .addGap(18, 18, 18)
                                .addComponent(phoneNumJText, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cityJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cityJText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(stateJLabel)
                                .addGap(18, 18, 18)
                                .addComponent(stateJText, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(zipCodeJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(zipCodeJText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(createReportJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dateExpiryJLabel)
                                        .addGap(0, 0, 0)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(dateExpiryJText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(54, 54, 54)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(dateIssueJLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(dateIssueJText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(bloodTypeJLabel)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(bloodTypeJText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(licenseNumJLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(licenseNumJText, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lincenseDetailsJLabel)
                                    .addComponent(medicalDetailsJLabel)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(alergy2JLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(alergy2JText, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(9, 9, 9))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(medicalRecordNumJLabel)
                                            .addGap(18, 18, 18)
                                            .addComponent(medicalRecordNumJText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(alergy1JLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(alergy1JText, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(alergy3JLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(alergy3JText, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(uploadeImageJButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(pictureJText, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ImageHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(604, 604, 604)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(demographicJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fNameJLabel)
                    .addComponent(fNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameJLabel)
                    .addComponent(lastNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phoneNumJLabel)
                    .addComponent(phoneNumJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobJLabel)
                    .addComponent(dobJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageJLabel)
                    .addComponent(ageJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heightJLabel)
                    .addComponent(heightJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightJLabel)
                    .addComponent(weightJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ssnJLabel)
                    .addComponent(ssnJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addressDetailsJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add1JLabel)
                    .addComponent(add1JText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add2JLabel)
                    .addComponent(add2JText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(zipCodeJLabel)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stateJLabel)
                        .addComponent(zipCodeJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cityJLabel)
                        .addComponent(cityJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(stateJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savingsAccountDetailsJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savingsBankNameJLabel)
                    .addComponent(savingsBankNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savingsAccBalnJLabel)
                    .addComponent(savingsAccBalnJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savingsAccNumJLabel)
                    .addComponent(savingsAccNumJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savingsAccTypeJLabel)
                    .addComponent(savingsRNumJLabel)
                    .addComponent(savingsRNumJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkingsBankNameJLabel)
                    .addComponent(checkingsBankNameJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkingsAccBalnJLabel)
                    .addComponent(checkingsAccBalnJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkingsAccNumJLabel)
                    .addComponent(checkingsAccNumJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkingsRNumJLabel)
                    .addComponent(checkingsRNumJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkingsAccTypeJLabel)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImageHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lincenseDetailsJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pictureJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uploadeImageJButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateIssueJLabel)
                            .addComponent(dateIssueJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(licenseNumJLabel)
                            .addComponent(licenseNumJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateExpiryJLabel)
                            .addComponent(dateExpiryJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodTypeJLabel)
                            .addComponent(bloodTypeJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(medicalDetailsJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medicalRecordNumJLabel)
                            .addComponent(medicalRecordNumJText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alergy1JLabel)
                            .addComponent(alergy1JText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alergy2JText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alergy2JLabel))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alergy3JLabel)
                            .addComponent(alergy3JText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(createReportJButton)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(107, 107, 107)))
        );

        ImageHolder.getAccessibleContext().setAccessibleDescription("");
        ImageHolder.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createReportJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createReportJButtonActionPerformed
        // Binding user inputs through this Button

        // Demographic information
        information.setfName(fNameJText.getText());
        information.setLastName(lastNameJText.getText());
        information.setPhoneNum(phoneNumJText.getText());
        information.setDob(dobJText.getText());
        information.setAge(ageJText.getText());
        information.setHeight(heightJText.getText());
        information.setWeight(weightJText.getText());
        information.setSsn(ssnJText.getText());

        // Address Information
        information.setAdd1(add1JText.getText());
        information.setAdd2(add2JText.getText());
        information.setCity(cityJText.getText());
        information.setState(stateJText.getText());
        information.setZipCode(zipCodeJText.getText());

        // Account Information
        information.setSavingsBankName(savingsBankNameJText.getText());
        information.setSavingsAccNum(savingsAccNumJText.getText());
        information.setSavingsRNum(savingsRNumJText.getText());
        information.setSavingsAccBaln(savingsAccBalnJText.getText());
        
        // Checkings Account Information
        information.setCheckingsBankName(checkingsBankNameJText.getText());
        information.setCheckingsAccNum(checkingsAccNumJText.getText());
        information.setCheckingsRNum(checkingsRNumJText.getText());
        information.setCheckingsAccBaln(checkingsAccBalnJText.getText());

        
        // License Information
        information.setLicenseNum(licenseNumJText.getText());
        information.setDateIssue(dateIssueJText.getText());
        information.setDateExpiry(dateExpiryJText.getText());
        information.setBloodType(bloodTypeJText.getText());
        information.setPicture(pictureJText.getText());

        // Medical Record information
        information.setMedicalRecordNum(medicalRecordNumJText.getText());
        information.setAlergy1(alergy1JText.getText());
        information.setAlergy2(alergy2JText.getText());
        information.setAlergy3(alergy3JText.getText());

        // Promt user that Record was Created!!
        JOptionPane.showMessageDialog(null, "Thank You for submitting all the Details. Please click on View to get your complete Report");
    }//GEN-LAST:event_createReportJButtonActionPerformed

    private void alergy3JTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alergy3JTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alergy3JTextActionPerformed

    private void alergy2JTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alergy2JTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alergy2JTextActionPerformed

    private void alergy1JTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alergy1JTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alergy1JTextActionPerformed

    private void bloodTypeJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodTypeJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodTypeJTextActionPerformed

    private void dateExpiryJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateExpiryJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateExpiryJTextActionPerformed

    private void dateIssueJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateIssueJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateIssueJTextActionPerformed

    private void pictureJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pictureJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pictureJTextActionPerformed

    private void uploadeImageJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadeImageJButtonActionPerformed
        // TODO add your handling code here:

        //Open File window
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showOpenDialog(null);
         //Select image
            File file = jFileChooser.getSelectedFile();
         //Get image path
            String selectedImage = file.getAbsolutePath();
         //success popup
            JOptionPane.showMessageDialog(null, selectedImage);
            pictureJText.setText(selectedImage);
         //Place image in Label
            ImageIcon icon = new ImageIcon(selectedImage);
            ImageHolder.setIcon(icon);

    }//GEN-LAST:event_uploadeImageJButtonActionPerformed

    private void savingsAccNumJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsAccNumJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsAccNumJTextActionPerformed

    private void savingsRNumJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsRNumJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsRNumJTextActionPerformed

    private void savingsAccBalnJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsAccBalnJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsAccBalnJTextActionPerformed

    private void zipCodeJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipCodeJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipCodeJTextActionPerformed

    private void stateJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateJTextActionPerformed

    private void cityJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityJTextActionPerformed

    private void add2JTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2JTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add2JTextActionPerformed

    private void ssnJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssnJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ssnJTextActionPerformed

    private void weightJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightJTextActionPerformed

    private void heightJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightJTextActionPerformed

    private void ageJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageJTextActionPerformed

    private void dobJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobJTextActionPerformed

    private void phoneNumJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumJTextActionPerformed

    private void lastNameJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameJTextActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        JComboBox cbox = (JComboBox) evt.getSource();
        Object option = cbox.getSelectedItem();
        information.setSavingsAccType(option.toString());        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void checkingsAccBalnJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingsAccBalnJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingsAccBalnJTextActionPerformed

    private void checkingsRNumJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingsRNumJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingsRNumJTextActionPerformed

    private void checkingsAccNumJTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingsAccNumJTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingsAccNumJTextActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        JComboBox sbox = (JComboBox) evt.getSource();
        Object option = sbox.getSelectedItem();
        information.setCheckingsAccType(option.toString());  
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageHolder;
    private javax.swing.JLabel add1JLabel;
    private javax.swing.JTextField add1JText;
    private javax.swing.JLabel add2JLabel;
    private javax.swing.JTextField add2JText;
    private javax.swing.JLabel addressDetailsJLabel;
    private javax.swing.JLabel ageJLabel;
    private javax.swing.JTextField ageJText;
    private javax.swing.JLabel alergy1JLabel;
    private javax.swing.JTextField alergy1JText;
    private javax.swing.JLabel alergy2JLabel;
    private javax.swing.JTextField alergy2JText;
    private javax.swing.JLabel alergy3JLabel;
    private javax.swing.JTextField alergy3JText;
    private javax.swing.JLabel bloodTypeJLabel;
    private javax.swing.JTextField bloodTypeJText;
    private javax.swing.JLabel checkingsAccBalnJLabel;
    private javax.swing.JTextField checkingsAccBalnJText;
    private javax.swing.JLabel checkingsAccNumJLabel;
    private javax.swing.JTextField checkingsAccNumJText;
    private javax.swing.JLabel checkingsAccTypeJLabel;
    private javax.swing.JLabel checkingsBankNameJLabel;
    private javax.swing.JTextField checkingsBankNameJText;
    private javax.swing.JLabel checkingsRNumJLabel;
    private javax.swing.JTextField checkingsRNumJText;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JTextField cityJText;
    private javax.swing.JButton createReportJButton;
    private javax.swing.JLabel dateExpiryJLabel;
    private javax.swing.JTextField dateExpiryJText;
    private javax.swing.JLabel dateIssueJLabel;
    private javax.swing.JTextField dateIssueJText;
    private javax.swing.JLabel demographicJLabel;
    private javax.swing.JLabel dobJLabel;
    private javax.swing.JTextField dobJText;
    private javax.swing.JLabel fNameJLabel;
    private javax.swing.JTextField fNameJText;
    private javax.swing.JLabel heightJLabel;
    private javax.swing.JTextField heightJText;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lastNameJLabel;
    private javax.swing.JTextField lastNameJText;
    private javax.swing.JLabel licenseNumJLabel;
    private javax.swing.JTextField licenseNumJText;
    private javax.swing.JLabel lincenseDetailsJLabel;
    private javax.swing.JLabel medicalDetailsJLabel;
    private javax.swing.JLabel medicalRecordNumJLabel;
    private javax.swing.JTextField medicalRecordNumJText;
    private javax.swing.JLabel phoneNumJLabel;
    private javax.swing.JTextField phoneNumJText;
    private javax.swing.JTextField pictureJText;
    private javax.swing.JLabel savingsAccBalnJLabel;
    private javax.swing.JTextField savingsAccBalnJText;
    private javax.swing.JLabel savingsAccNumJLabel;
    private javax.swing.JTextField savingsAccNumJText;
    private javax.swing.JLabel savingsAccTypeJLabel;
    private javax.swing.JLabel savingsAccountDetailsJLabel;
    private javax.swing.JLabel savingsBankNameJLabel;
    private javax.swing.JTextField savingsBankNameJText;
    private javax.swing.JLabel savingsRNumJLabel;
    private javax.swing.JTextField savingsRNumJText;
    private javax.swing.JLabel ssnJLabel;
    private javax.swing.JTextField ssnJText;
    private javax.swing.JLabel stateJLabel;
    private javax.swing.JTextField stateJText;
    private javax.swing.JButton uploadeImageJButton;
    private javax.swing.JLabel weightJLabel;
    private javax.swing.JTextField weightJText;
    private javax.swing.JLabel zipCodeJLabel;
    private javax.swing.JTextField zipCodeJText;
    // End of variables declaration//GEN-END:variables
}
